name: Flutter_Android

on:
  push:
    branches: [master]

jobs:
 build_android:
   runs-on: ubuntu-latest

   steps:
    - name: Checkout the code
      uses: actions/checkout@v3
      
    - name: Setup Java to compile Android project
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    
    - name: Install and set Flutter version
      uses: subosito/flutter-action@v1.4.0
      with:
        flutter-version: '3.0.0'
    
    - name: Check Flutter
      run: flutter doctor
